name: Deploy index.html to EC2
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'

  push:
    branches:
      - main  # adjust based on your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -v ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo ✅ Connected"

      - name: Deploy index.php to /tmp on EC2
        run: |
          scp index.php ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/index.php
